version: 2

sphinx:
  configuration: doc/conf.py

formats: all

build:
  apt_packages:
    - libgmp-dev

python:
  version: 3.8
  install:
    - requirements: doc/requirements.txt
    - method: setuptools
      path: "."


